# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: erroranalysis.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='erroranalysis.proto',
  package='com.ices.sh.quality.rpc',
  syntax='proto3',
  serialized_options=_b('\n\027com.ices.sh.quality.rpcB\nQualityRpc'),
  serialized_pb=_b('\n\x13\x65rroranalysis.proto\x12\x17\x63om.ices.sh.quality.rpc\x1a\x1egoogle/protobuf/wrappers.proto2]\n\x0eQualityService\x12K\n\rerrorAnalysis\x12\x1c.google.protobuf.StringValue\x1a\x1c.google.protobuf.StringValueB%\n\x17\x63om.ices.sh.quality.rpcB\nQualityRpcb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_QUALITYSERVICE = _descriptor.ServiceDescriptor(
  name='QualityService',
  full_name='com.ices.sh.quality.rpc.QualityService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=80,
  serialized_end=173,
  methods=[
  _descriptor.MethodDescriptor(
    name='errorAnalysis',
    full_name='com.ices.sh.quality.rpc.QualityService.errorAnalysis',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE,
    output_type=google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_QUALITYSERVICE)

DESCRIPTOR.services_by_name['QualityService'] = _QUALITYSERVICE

# @@protoc_insertion_point(module_scope)
